# Site settings
title: Seed 
email: seedlitmag@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The Grissom High School Arts & Literature Magazine
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
